name: Deployment pipeline

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Install gh-pages
        run: npm install gh-pages --save-dev

      - name: Check style
        run: npm run eslint

      - name: Build app
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e
        
      - name: Upload report
        run: npm run upload-report 

      - name: Trigger Render deployment
        if: ${{ github.event_name == 'push' &&  !contains(join(github.event.commits.*.message),'#skip')  }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Discord Success Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: success()
        with:
           args: 'The project ${{ github.repository }} has been deployed.'
        
      - name: Discord Failure Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        if: failure()
        with:
           args: 'The project ${{ github.repository  }} has failed to deploy. Commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.name }} has broken the build!'


     
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' &&  !contains(join(github.event.commits.*.message),'#skip') }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#      - uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
#        with:
#          name: playwright-report
#          path: playwright-report/
#s          retention-days: 30

